project_id = "flashlearn"

[api]
enabled = true
port = 64721
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 64722
major_version = 15

[studio]
enabled = true
port = 64723

[inbucket]
enabled = true
port = 64724

[storage]
enabled = true
file_size_limit = "5MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = [
  "http://127.0.0.1:3000",
  "http://127.0.0.1:3000/auth/confirm",
]

[auth.email]
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Xác nhận email của bạn | FlashLearn"
content_path = "./supabase/templates/confirm-email.html"

[analytics]
enabled = false

[functions.send-reminders]
verify_jwt = false
