import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/lib/supabase/types.ts",
    // Generated by Serwist during the production build.
    "public/sw.js",
    "public/sw.js.map",
    // Deno edge functions use npm: specifiers + Deno globals — not part of
    // the Next.js runtime, so they are excluded from lint/typecheck.
    "supabase/functions/**",
    "supabase/.branches/**",
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
