export interface TimezoneOption {
  value: string;
  label: string;
  group: string;
}

const GROUP_UTC = "UTC";
const GROUP_ASIA = "Châu Á";
const GROUP_EUROPE = "Châu Âu";
const GROUP_AFRICA = "Châu Phi";
const GROUP_NORTH_AMERICA = "Bắc Mỹ";
const GROUP_SOUTH_AMERICA = "Nam Mỹ";
const GROUP_ATLANTIC = "Đại Tây Dương";
const GROUP_AUSTRALIA = "Châu Đại Dương";
const GROUP_PACIFIC = "Thái Bình Dương";
const GROUP_INDIAN = "Ấn Độ Dương";

const TZ = (value: string, group: string): TimezoneOption => ({
  value,
  label: value,
  group,
});

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  TZ("UTC", GROUP_UTC),

  TZ("Asia/Ho_Chi_Minh", GROUP_ASIA),
  TZ("Asia/Bangkok", GROUP_ASIA),
  TZ("Asia/Phnom_Penh", GROUP_ASIA),
  TZ("Asia/Vientiane", GROUP_ASIA),
  TZ("Asia/Jakarta", GROUP_ASIA),
  TZ("Asia/Pontianak", GROUP_ASIA),
  TZ("Asia/Makassar", GROUP_ASIA),
  TZ("Asia/Jayapura", GROUP_ASIA),
  TZ("Asia/Singapore", GROUP_ASIA),
  TZ("Asia/Kuala_Lumpur", GROUP_ASIA),
  TZ("Asia/Brunei", GROUP_ASIA),
  TZ("Asia/Manila", GROUP_ASIA),
  TZ("Asia/Hong_Kong", GROUP_ASIA),
  TZ("Asia/Shanghai", GROUP_ASIA),
  TZ("Asia/Taipei", GROUP_ASIA),
  TZ("Asia/Macau", GROUP_ASIA),
  TZ("Asia/Tokyo", GROUP_ASIA),
  TZ("Asia/Seoul", GROUP_ASIA),
  TZ("Asia/Pyongyang", GROUP_ASIA),
  TZ("Asia/Yangon", GROUP_ASIA),
  TZ("Asia/Dhaka", GROUP_ASIA),
  TZ("Asia/Thimphu", GROUP_ASIA),
  TZ("Asia/Kathmandu", GROUP_ASIA),
  TZ("Asia/Kolkata", GROUP_ASIA),
  TZ("Asia/Colombo", GROUP_ASIA),
  TZ("Asia/Karachi", GROUP_ASIA),
  TZ("Asia/Kabul", GROUP_ASIA),
  TZ("Asia/Dushanbe", GROUP_ASIA),
  TZ("Asia/Tashkent", GROUP_ASIA),
  TZ("Asia/Samarkand", GROUP_ASIA),
  TZ("Asia/Bishkek", GROUP_ASIA),
  TZ("Asia/Ashgabat", GROUP_ASIA),
  TZ("Asia/Baku", GROUP_ASIA),
  TZ("Asia/Tbilisi", GROUP_ASIA),
  TZ("Asia/Yerevan", GROUP_ASIA),
  TZ("Asia/Tehran", GROUP_ASIA),
  TZ("Asia/Baghdad", GROUP_ASIA),
  TZ("Asia/Riyadh", GROUP_ASIA),
  TZ("Asia/Kuwait", GROUP_ASIA),
  TZ("Asia/Qatar", GROUP_ASIA),
  TZ("Asia/Bahrain", GROUP_ASIA),
  TZ("Asia/Dubai", GROUP_ASIA),
  TZ("Asia/Muscat", GROUP_ASIA),
  TZ("Asia/Aden", GROUP_ASIA),
  TZ("Asia/Amman", GROUP_ASIA),
  TZ("Asia/Beirut", GROUP_ASIA),
  TZ("Asia/Damascus", GROUP_ASIA),
  TZ("Asia/Gaza", GROUP_ASIA),
  TZ("Asia/Jerusalem", GROUP_ASIA),
  TZ("Asia/Nicosia", GROUP_ASIA),
  TZ("Asia/Famagusta", GROUP_ASIA),
  TZ("Asia/Almaty", GROUP_ASIA),
  TZ("Asia/Qostanay", GROUP_ASIA),
  TZ("Asia/Aqtobe", GROUP_ASIA),
  TZ("Asia/Aqtau", GROUP_ASIA),
  TZ("Asia/Ulaanbaatar", GROUP_ASIA),
  TZ("Asia/Hovd", GROUP_ASIA),
  TZ("Asia/Choibalsan", GROUP_ASIA),
  TZ("Asia/Novosibirsk", GROUP_ASIA),
  TZ("Asia/Omsk", GROUP_ASIA),
  TZ("Asia/Krasnoyarsk", GROUP_ASIA),
  TZ("Asia/Irkutsk", GROUP_ASIA),
  TZ("Asia/Yakutsk", GROUP_ASIA),
  TZ("Asia/Vladivostok", GROUP_ASIA),
  TZ("Asia/Sakhalin", GROUP_ASIA),
  TZ("Asia/Magadan", GROUP_ASIA),
  TZ("Asia/Kamchatka", GROUP_ASIA),
  TZ("Asia/Anadyr", GROUP_ASIA),
  TZ("Asia/Dili", GROUP_ASIA),
  TZ("Asia/Yekaterinburg", GROUP_ASIA),

  TZ("Europe/London", GROUP_EUROPE),
  TZ("Europe/Dublin", GROUP_EUROPE),
  TZ("Europe/Lisbon", GROUP_EUROPE),
  TZ("Europe/Madrid", GROUP_EUROPE),
  TZ("Europe/Paris", GROUP_EUROPE),
  TZ("Europe/Brussels", GROUP_EUROPE),
  TZ("Europe/Amsterdam", GROUP_EUROPE),
  TZ("Europe/Luxembourg", GROUP_EUROPE),
  TZ("Europe/Monaco", GROUP_EUROPE),
  TZ("Europe/Berlin", GROUP_EUROPE),
  TZ("Europe/Vienna", GROUP_EUROPE),
  TZ("Europe/Zurich", GROUP_EUROPE),
  TZ("Europe/Rome", GROUP_EUROPE),
  TZ("Europe/Copenhagen", GROUP_EUROPE),
  TZ("Europe/Stockholm", GROUP_EUROPE),
  TZ("Europe/Oslo", GROUP_EUROPE),
  TZ("Europe/Prague", GROUP_EUROPE),
  TZ("Europe/Warsaw", GROUP_EUROPE),
  TZ("Europe/Budapest", GROUP_EUROPE),
  TZ("Europe/Bratislava", GROUP_EUROPE),
  TZ("Europe/Ljubljana", GROUP_EUROPE),
  TZ("Europe/Zagreb", GROUP_EUROPE),
  TZ("Europe/Sarajevo", GROUP_EUROPE),
  TZ("Europe/Skopje", GROUP_EUROPE),
  TZ("Europe/Podgorica", GROUP_EUROPE),
  TZ("Europe/Belgrade", GROUP_EUROPE),
  TZ("Europe/Tirane", GROUP_EUROPE),
  TZ("Europe/Sofia", GROUP_EUROPE),
  TZ("Europe/Bucharest", GROUP_EUROPE),
  TZ("Europe/Athens", GROUP_EUROPE),
  TZ("Europe/Chisinau", GROUP_EUROPE),
  TZ("Europe/Kyiv", GROUP_EUROPE),
  TZ("Europe/Minsk", GROUP_EUROPE),
  TZ("Europe/Moscow", GROUP_EUROPE),
  TZ("Europe/Kaliningrad", GROUP_EUROPE),
  TZ("Europe/Volgograd", GROUP_EUROPE),
  TZ("Europe/Astrakhan", GROUP_EUROPE),
  TZ("Europe/Ulyanovsk", GROUP_EUROPE),
  TZ("Europe/Saratov", GROUP_EUROPE),
  TZ("Europe/Kirov", GROUP_EUROPE),
  TZ("Europe/Samara", GROUP_EUROPE),
  TZ("Europe/Simferopol", GROUP_EUROPE),
  TZ("Europe/Istanbul", GROUP_EUROPE),
  TZ("Europe/Helsinki", GROUP_EUROPE),
  TZ("Europe/Tallinn", GROUP_EUROPE),
  TZ("Europe/Riga", GROUP_EUROPE),
  TZ("Europe/Vilnius", GROUP_EUROPE),
  TZ("Europe/Uzhgorod", GROUP_EUROPE),
  TZ("Europe/Zaporozhye", GROUP_EUROPE),
  TZ("Europe/Isle_of_Man", GROUP_EUROPE),
  TZ("Europe/Guernsey", GROUP_EUROPE),
  TZ("Europe/Jersey", GROUP_EUROPE),
  TZ("Europe/Gibraltar", GROUP_EUROPE),
  TZ("Europe/Malta", GROUP_EUROPE),
  TZ("Europe/Andorra", GROUP_EUROPE),
  TZ("Europe/Vaduz", GROUP_EUROPE),
  TZ("Europe/San_Marino", GROUP_EUROPE),
  TZ("Europe/Busingen", GROUP_EUROPE),

  TZ("Africa/Cairo", GROUP_AFRICA),
  TZ("Africa/Casablanca", GROUP_AFRICA),
  TZ("Africa/El_Aaiun", GROUP_AFRICA),
  TZ("Africa/Tunis", GROUP_AFRICA),
  TZ("Africa/Algiers", GROUP_AFRICA),
  TZ("Africa/Tripoli", GROUP_AFRICA),
  TZ("Africa/Ndjamena", GROUP_AFRICA),
  TZ("Africa/Nouakchott", GROUP_AFRICA),
  TZ("Africa/Banjul", GROUP_AFRICA),
  TZ("Africa/Dakar", GROUP_AFRICA),
  TZ("Africa/Bamako", GROUP_AFRICA),
  TZ("Africa/Conakry", GROUP_AFRICA),
  TZ("Africa/Freetown", GROUP_AFRICA),
  TZ("Africa/Monrovia", GROUP_AFRICA),
  TZ("Africa/Abidjan", GROUP_AFRICA),
  TZ("Africa/Accra", GROUP_AFRICA),
  TZ("Africa/Lome", GROUP_AFRICA),
  TZ("Africa/Ouagadougou", GROUP_AFRICA),
  TZ("Africa/Niamey", GROUP_AFRICA),
  TZ("Africa/Sao_Tome", GROUP_AFRICA),
  TZ("Africa/Bissau", GROUP_AFRICA),
  TZ("Africa/Lagos", GROUP_AFRICA),
  TZ("Africa/Porto-Novo", GROUP_AFRICA),
  TZ("Africa/Libreville", GROUP_AFRICA),
  TZ("Africa/Malabo", GROUP_AFRICA),
  TZ("Africa/Brazzaville", GROUP_AFRICA),
  TZ("Africa/Kinshasa", GROUP_AFRICA),
  TZ("Africa/Luanda", GROUP_AFRICA),
  TZ("Africa/Kigali", GROUP_AFRICA),
  TZ("Africa/Bujumbura", GROUP_AFRICA),
  TZ("Africa/Lusaka", GROUP_AFRICA),
  TZ("Africa/Harare", GROUP_AFRICA),
  TZ("Africa/Gaborone", GROUP_AFRICA),
  TZ("Africa/Maseru", GROUP_AFRICA),
  TZ("Africa/Mbabane", GROUP_AFRICA),
  TZ("Africa/Johannesburg", GROUP_AFRICA),
  TZ("Africa/Maputo", GROUP_AFRICA),
  TZ("Africa/Dar_es_Salaam", GROUP_AFRICA),
  TZ("Africa/Djibouti", GROUP_AFRICA),
  TZ("Africa/Asmara", GROUP_AFRICA),
  TZ("Africa/Addis_Ababa", GROUP_AFRICA),
  TZ("Africa/Mogadishu", GROUP_AFRICA),
  TZ("Africa/Nairobi", GROUP_AFRICA),
  TZ("Africa/Kampala", GROUP_AFRICA),
  TZ("Africa/Khartoum", GROUP_AFRICA),
  TZ("Africa/Juba", GROUP_AFRICA),
  TZ("Africa/Blantyre", GROUP_AFRICA),
  TZ("Africa/Windhoek", GROUP_AFRICA),
  TZ("Africa/Lubumbashi", GROUP_AFRICA),

  TZ("America/New_York", GROUP_NORTH_AMERICA),
  TZ("America/Chicago", GROUP_NORTH_AMERICA),
  TZ("America/Denver", GROUP_NORTH_AMERICA),
  TZ("America/Los_Angeles", GROUP_NORTH_AMERICA),
  TZ("America/Phoenix", GROUP_NORTH_AMERICA),
  TZ("America/Anchorage", GROUP_NORTH_AMERICA),
  TZ("America/Juneau", GROUP_NORTH_AMERICA),
  TZ("America/Nome", GROUP_NORTH_AMERICA),
  TZ("America/Sitka", GROUP_NORTH_AMERICA),
  TZ("America/Yakutat", GROUP_NORTH_AMERICA),
  TZ("America/Adak", GROUP_NORTH_AMERICA),
  TZ("America/Detroit", GROUP_NORTH_AMERICA),
  TZ("America/Boise", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Indianapolis", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Knox", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Marengo", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Petersburg", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Tell_City", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Vevay", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Vincennes", GROUP_NORTH_AMERICA),
  TZ("America/Indiana/Winamac", GROUP_NORTH_AMERICA),
  TZ("America/Kentucky/Louisville", GROUP_NORTH_AMERICA),
  TZ("America/Kentucky/Monticello", GROUP_NORTH_AMERICA),
  TZ("America/Menominee", GROUP_NORTH_AMERICA),
  TZ("America/North_Dakota/Center", GROUP_NORTH_AMERICA),
  TZ("America/North_Dakota/New_Salem", GROUP_NORTH_AMERICA),
  TZ("America/North_Dakota/Beulah", GROUP_NORTH_AMERICA),
  TZ("America/Toronto", GROUP_NORTH_AMERICA),
  TZ("America/Vancouver", GROUP_NORTH_AMERICA),
  TZ("America/Edmonton", GROUP_NORTH_AMERICA),
  TZ("America/Regina", GROUP_NORTH_AMERICA),
  TZ("America/Winnipeg", GROUP_NORTH_AMERICA),
  TZ("America/Thunder_Bay", GROUP_NORTH_AMERICA),
  TZ("America/St_Johns", GROUP_NORTH_AMERICA),
  TZ("America/Halifax", GROUP_NORTH_AMERICA),
  TZ("America/Glace_Bay", GROUP_NORTH_AMERICA),
  TZ("America/Goose_Bay", GROUP_NORTH_AMERICA),
  TZ("America/Blanc-Sablon", GROUP_NORTH_AMERICA),
  TZ("America/Iqaluit", GROUP_NORTH_AMERICA),
  TZ("America/Moncton", GROUP_NORTH_AMERICA),
  TZ("America/Nipigon", GROUP_NORTH_AMERICA),
  TZ("America/Pangnirtung", GROUP_NORTH_AMERICA),
  TZ("America/Rainy_River", GROUP_NORTH_AMERICA),
  TZ("America/Rankin_Inlet", GROUP_NORTH_AMERICA),
  TZ("America/Resolute", GROUP_NORTH_AMERICA),
  TZ("America/Yellowknife", GROUP_NORTH_AMERICA),
  TZ("America/Inuvik", GROUP_NORTH_AMERICA),
  TZ("America/Creston", GROUP_NORTH_AMERICA),
  TZ("America/Dawson", GROUP_NORTH_AMERICA),
  TZ("America/Dawson_Creek", GROUP_NORTH_AMERICA),
  TZ("America/Fort_Nelson", GROUP_NORTH_AMERICA),
  TZ("America/Whitehorse", GROUP_NORTH_AMERICA),
  TZ("America/Mexico_City", GROUP_NORTH_AMERICA),
  TZ("America/Cancun", GROUP_NORTH_AMERICA),
  TZ("America/Costa_Rica", GROUP_NORTH_AMERICA),
  TZ("America/El_Salvador", GROUP_NORTH_AMERICA),
  TZ("America/Guatemala", GROUP_NORTH_AMERICA),
  TZ("America/Managua", GROUP_NORTH_AMERICA),
  TZ("America/Panama", GROUP_NORTH_AMERICA),
  TZ("America/Tegucigalpa", GROUP_NORTH_AMERICA),
  TZ("America/Belize", GROUP_NORTH_AMERICA),
  TZ("America/Havana", GROUP_NORTH_AMERICA),
  TZ("America/Jamaica", GROUP_NORTH_AMERICA),
  TZ("America/Nassau", GROUP_NORTH_AMERICA),
  TZ("America/Puerto_Rico", GROUP_NORTH_AMERICA),
  TZ("America/Port-au-Prince", GROUP_NORTH_AMERICA),
  TZ("America/Santo_Domingo", GROUP_NORTH_AMERICA),
  TZ("America/Grand_Turk", GROUP_NORTH_AMERICA),
  TZ("America/Barbados", GROUP_NORTH_AMERICA),
  TZ("America/Curacao", GROUP_NORTH_AMERICA),
  TZ("America/Aruba", GROUP_NORTH_AMERICA),
  TZ("America/Port_of_Spain", GROUP_NORTH_AMERICA),
  TZ("America/Chihuahua", GROUP_NORTH_AMERICA),
  TZ("America/Hermosillo", GROUP_NORTH_AMERICA),
  TZ("America/Mazatlan", GROUP_NORTH_AMERICA),
  TZ("America/Tijuana", GROUP_NORTH_AMERICA),
  TZ("America/Ojinaga", GROUP_NORTH_AMERICA),
  TZ("America/Bahia_Banderas", GROUP_NORTH_AMERICA),
  TZ("America/Miquelon", GROUP_NORTH_AMERICA),

  TZ("America/Bogota", GROUP_SOUTH_AMERICA),
  TZ("America/Lima", GROUP_SOUTH_AMERICA),
  TZ("America/Guayaquil", GROUP_SOUTH_AMERICA),
  TZ("America/Caracas", GROUP_SOUTH_AMERICA),
  TZ("America/La_Paz", GROUP_SOUTH_AMERICA),
  TZ("America/Asuncion", GROUP_SOUTH_AMERICA),
  TZ("America/Manaus", GROUP_SOUTH_AMERICA),
  TZ("America/Cuiaba", GROUP_SOUTH_AMERICA),
  TZ("America/Campo_Grande", GROUP_SOUTH_AMERICA),
  TZ("America/Porto_Velho", GROUP_SOUTH_AMERICA),
  TZ("America/Belem", GROUP_SOUTH_AMERICA),
  TZ("America/Fortaleza", GROUP_SOUTH_AMERICA),
  TZ("America/Recife", GROUP_SOUTH_AMERICA),
  TZ("America/Bahia", GROUP_SOUTH_AMERICA),
  TZ("America/Santarem", GROUP_SOUTH_AMERICA),
  TZ("America/Sao_Paulo", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Buenos_Aires", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Cordoba", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Salta", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Jujuy", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Tucuman", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Catamarca", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/La_Rioja", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/San_Juan", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Mendoza", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/San_Luis", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Rio_Gallegos", GROUP_SOUTH_AMERICA),
  TZ("America/Argentina/Ushuaia", GROUP_SOUTH_AMERICA),
  TZ("America/Santiago", GROUP_SOUTH_AMERICA),
  TZ("America/Punta_Arenas", GROUP_SOUTH_AMERICA),
  TZ("America/Montevideo", GROUP_SOUTH_AMERICA),
  TZ("America/Guyana", GROUP_SOUTH_AMERICA),
  TZ("America/Paramaribo", GROUP_SOUTH_AMERICA),
  TZ("America/Cayenne", GROUP_SOUTH_AMERICA),

  TZ("Atlantic/Reykjavik", GROUP_ATLANTIC),
  TZ("Atlantic/Azores", GROUP_ATLANTIC),
  TZ("Atlantic/Canary", GROUP_ATLANTIC),
  TZ("Atlantic/Madeira", GROUP_ATLANTIC),
  TZ("Atlantic/Cape_Verde", GROUP_ATLANTIC),
  TZ("Atlantic/Bermuda", GROUP_ATLANTIC),
  TZ("Atlantic/Faroe", GROUP_ATLANTIC),
  TZ("Atlantic/Stanley", GROUP_ATLANTIC),
  TZ("Atlantic/South_Georgia", GROUP_ATLANTIC),
  TZ("Atlantic/St_Helena", GROUP_ATLANTIC),

  TZ("Australia/Sydney", GROUP_AUSTRALIA),
  TZ("Australia/Melbourne", GROUP_AUSTRALIA),
  TZ("Australia/Brisbane", GROUP_AUSTRALIA),
  TZ("Australia/Lindeman", GROUP_AUSTRALIA),
  TZ("Australia/Adelaide", GROUP_AUSTRALIA),
  TZ("Australia/Darwin", GROUP_AUSTRALIA),
  TZ("Australia/Perth", GROUP_AUSTRALIA),
  TZ("Australia/Eucla", GROUP_AUSTRALIA),
  TZ("Australia/Hobart", GROUP_AUSTRALIA),
  TZ("Australia/Currie", GROUP_AUSTRALIA),
  TZ("Australia/Lord_Howe", GROUP_AUSTRALIA),
  TZ("Australia/Broken_Hill", GROUP_AUSTRALIA),

  TZ("Pacific/Auckland", GROUP_PACIFIC),
  TZ("Pacific/Chatham", GROUP_PACIFIC),
  TZ("Pacific/Fiji", GROUP_PACIFIC),
  TZ("Pacific/Tongatapu", GROUP_PACIFIC),
  TZ("Pacific/Apia", GROUP_PACIFIC),
  TZ("Pacific/Honolulu", GROUP_PACIFIC),
  TZ("Pacific/Rarotonga", GROUP_PACIFIC),
  TZ("Pacific/Niue", GROUP_PACIFIC),
  TZ("Pacific/Pago_Pago", GROUP_PACIFIC),
  TZ("Pacific/Pitcairn", GROUP_PACIFIC),
  TZ("Pacific/Marquesas", GROUP_PACIFIC),
  TZ("Pacific/Gambier", GROUP_PACIFIC),
  TZ("Pacific/Tahiti", GROUP_PACIFIC),
  TZ("Pacific/Galapagos", GROUP_PACIFIC),
  TZ("Pacific/Easter", GROUP_PACIFIC),
  TZ("Pacific/Guam", GROUP_PACIFIC),
  TZ("Pacific/Saipan", GROUP_PACIFIC),
  TZ("Pacific/Port_Moresby", GROUP_PACIFIC),
  TZ("Pacific/Noumea", GROUP_PACIFIC),
  TZ("Pacific/Norfolk", GROUP_PACIFIC),
  TZ("Pacific/Funafuti", GROUP_PACIFIC),
  TZ("Pacific/Tarawa", GROUP_PACIFIC),
  TZ("Pacific/Enderbury", GROUP_PACIFIC),
  TZ("Pacific/Kiritimati", GROUP_PACIFIC),
  TZ("Pacific/Majuro", GROUP_PACIFIC),
  TZ("Pacific/Kwajalein", GROUP_PACIFIC),
  TZ("Pacific/Chuuk", GROUP_PACIFIC),
  TZ("Pacific/Pohnpei", GROUP_PACIFIC),
  TZ("Pacific/Kosrae", GROUP_PACIFIC),
  TZ("Pacific/Palau", GROUP_PACIFIC),
  TZ("Pacific/Nauru", GROUP_PACIFIC),
  TZ("Pacific/Wake", GROUP_PACIFIC),

  TZ("Indian/Maldives", GROUP_INDIAN),
  TZ("Indian/Mauritius", GROUP_INDIAN),
  TZ("Indian/Reunion", GROUP_INDIAN),
  TZ("Indian/Comoro", GROUP_INDIAN),
  TZ("Indian/Mayotte", GROUP_INDIAN),
  TZ("Indian/Antananarivo", GROUP_INDIAN),
  TZ("Indian/Christmas", GROUP_INDIAN),
  TZ("Indian/Cocos", GROUP_INDIAN),
  TZ("Indian/Kerguelen", GROUP_INDIAN),
  TZ("Indian/Chagos", GROUP_INDIAN),
];

const SUPPORTED_TIMEZONES = new Set(TIMEZONE_OPTIONS.map((option) => option.value));

export interface TimezoneGroup {
  group: string;
  options: TimezoneOption[];
}

export const TIMEZONE_GROUPS: TimezoneGroup[] = TIMEZONE_OPTIONS.reduce<TimezoneGroup[]>(
  (groups, option) => {
    const existing = groups.find((group) => group.group === option.group);
    if (existing) {
      existing.options.push(option);
    } else {
      groups.push({ group: option.group, options: [option] });
    }
    return groups;
  },
  [],
);

export function isSupportedTimezone(value: string): boolean {
  return SUPPORTED_TIMEZONES.has(value);
}

export function findTimezone(value: string): TimezoneOption | undefined {
  return TIMEZONE_OPTIONS.find((option) => option.value === value);
}
